"""T5 remote command definitions for GWM Jolion."""

from __future__ import annotations

COMMANDS: dict[str, dict] = {
    "start_engine": {
        "key": "start_engine",
        "name": "Запустить двигатель",
        "expected_remote_type": "0x03",
        "icon": "mdi:engine",
        "instructions": {"0x03": {"operationTime": "15", "switchOrder": "1"}},
        "operation_time_path": ("0x03", "operationTime"),
        "experimental": False,
    },
    "stop_engine": {
        "key": "stop_engine",
        "name": "Остановить двигатель",
        "expected_remote_type": "0x03",
        "icon": "mdi:engine-off",
        "instructions": {"0x03": {"operationTime": "15", "switchOrder": "2"}},
        "experimental": False,
    },
    "flash_lights": {
        "key": "flash_lights",
        "name": "Моргнуть фарами",
        "expected_remote_type": "0x06",
        "icon": "mdi:car-light-high",
        "instructions": {"0x06": {"search": {"whistle": "0", "flashing": "1"}}},
        "experimental": False,
    },
    "horn": {
        "key": "horn",
        "name": "Подать звуковой сигнал",
        "expected_remote_type": "0x06",
        "icon": "mdi:bugle",
        "instructions": {"0x06": {"search": {"whistle": "1", "flashing": "0"}}},
        "experimental": False,
    },
    "flash_and_horn": {
        "key": "flash_and_horn",
        "name": "Моргнуть фарами и подать сигнал",
        "expected_remote_type": "0x06",
        "icon": "mdi:car-light-high",
        "instructions": {"0x06": {"search": {"whistle": "1", "flashing": "1"}}},
        "experimental": False,
    },
    "unlock_vehicle": {
        "key": "unlock_vehicle",
        "name": "Открыть двери",
        "expected_remote_type": "0x05",
        "icon": "mdi:car-door-lock-open",
        "instructions": {"0x05": {"switchOrder": "1", "operationTime": "0"}},
        "experimental": False,
    },
    "lock_vehicle": {
        "key": "lock_vehicle",
        "name": "Закрыть двери",
        "expected_remote_type": "0x05",
        "icon": "mdi:car-door-lock",
        "instructions": {"0x05": {"switchOrder": "2", "operationTime": "0"}},
        "experimental": False,
    },
    "open_trunk": {
        "key": "open_trunk",
        "name": "Открыть багажник",
        "expected_remote_type": "0x09",
        "icon": "mdi:car-back",
        "instructions": {"0x09": {"switchOrder": "1", "operationTime": "0"}},
        "experimental": False,
    },
    "close_trunk": {
        "key": "close_trunk",
        "name": "Закрыть багажник",
        "expected_remote_type": "0x09",
        "icon": "mdi:car-back",
        "instructions": {"0x09": {"switchOrder": "2", "operationTime": "0"}},
        "experimental": False,
    },
    "close_windows": {
        "key": "close_windows",
        "name": "Закрыть окна",
        "expected_remote_type": "0x08",
        "icon": "mdi:car-door",
        "instructions": {
            "0x08": {
                "switchOrder": "2",
                "window": {
                    "leftFront": 0,
                    "leftBack": 0,
                    "rightFront": 0,
                    "rightBack": 0,
                },
            }
        },
        "experimental": False,
    },
    "close_sunroof": {
        "key": "close_sunroof",
        "name": "Закрыть люк",
        "expected_remote_type": "0x08",
        "icon": "mdi:car-select",
        "instructions": {"0x08": {"switchOrder": "2", "window": {"skyLight": 0}}},
        "experimental": True,
    },
    "open_sunroof": {
        "key": "open_sunroof",
        "name": "Открыть люк",
        "expected_remote_type": "0x08",
        "icon": "mdi:car-select",
        "instructions": {"0x08": {"switchOrder": "1", "window": {"skyLight": 10}}},
        "experimental": True,
    },
    "open_sunshade": {
        "key": "open_sunshade",
        "name": "Открыть шторку люка",
        "expected_remote_type": "0x08",
        "icon": "mdi:blinds-open",
        "instructions": {"0x08": {"switchOrder": "1", "window": {"shadeScreen": 10}}},
        "experimental": True,
    },
    "close_sunshade": {
        "key": "close_sunshade",
        "name": "Закрыть шторку люка",
        "expected_remote_type": "0x08",
        "icon": "mdi:blinds-vertical-closed",
        "instructions": {"0x08": {"switchOrder": "2", "window": {}}},
        "experimental": True,
    },
    "rear_defrost_on": {
        "key": "rear_defrost_on",
        "name": "Включить обогрев заднего стекла",
        "expected_remote_type": "0x0B",
        "icon": "mdi:car-defrost-rear",
        "instructions": {
            "0x0B": {
                "defrost": {
                    "switchOrder": "1",
                    "operationTime": "10",
                    "defrostBack": "1",
                }
            }
        },
        "operation_time_path": ("0x0B", "defrost", "operationTime"),
        "experimental": False,
    },
    "rear_defrost_off": {
        "key": "rear_defrost_off",
        "name": "Выключить обогрев заднего стекла",
        "expected_remote_type": "0x0B",
        "icon": "mdi:car-defrost-rear",
        "instructions": {"0x0B": {"defrost": {"switchOrder": "2", "defrostBack": "1"}}},
        "experimental": False,
    },
    "steering_wheel_heat_on": {
        "key": "steering_wheel_heat_on",
        "name": "Включить обогрев руля",
        "expected_remote_type": "0x19",
        "icon": "mdi:steering",
        "instructions": {"0x19": {"switchOrder": "1", "operationTime": "10"}},
        "operation_time_path": ("0x19", "operationTime"),
        "experimental": False,
    },
    "steering_wheel_heat_off": {
        "key": "steering_wheel_heat_off",
        "name": "Выключить обогрев руля",
        "expected_remote_type": "0x19",
        "icon": "mdi:steering",
        "instructions": {"0x19": {"switchOrder": "2", "operationTime": "0"}},
        "experimental": False,
    },
    "front_defrost_on": {
        "key": "front_defrost_on",
        "name": "Включить обдув лобового (эксперимент)",
        "expected_remote_type": "0x0B",
        "icon": "mdi:car-defrost-front",
        "instructions": {"0x0B": {"defrost": {"defrostFront": 1, "operationTime": "900", "switchOrder": "1"}}},
        "experimental": True,
    },
    "front_defrost_off": {
        "key": "front_defrost_off",
        "name": "Выключить обдув лобового (эксперимент)",
        "expected_remote_type": "0x0B",
        "icon": "mdi:car-defrost-front",
        "instructions": {"0x0B": {"defrost": {"defrostFront": 0, "operationTime": "0", "switchOrder": "1"}}},
        "experimental": True,
    },
    "cabin_clean": {
        "key": "cabin_clean",
        "name": "Проветрить салон 60 сек (эксперимент)",
        "expected_remote_type": "0x11",
        "icon": "mdi:air-filter",
        "instructions": {"0x11": {"operationTime": "60", "switchOrder": "1"}},
        "experimental": True,
    },
}
